## Basic Configuration
baseurl = "https://paulovich.net/"
languageCode = "en"
title = "Paulovich.NET"
theme = "hugo-lamp"
copyright = "Ivan Paulovich"
disqusShortname = "paulovichdotnet"
googleAnalytics = "UA-27176166-1"

[Privacy]

[Privacy.disqus]
    disable = false

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Ivan Paulovich"
    profile = "https://github.com/ivanpaulovich"

[Taxonomies]
    tag = "tags"

## Site Settings
[params]
    logo = "/img/avatar.jpg"
    intro = true
    headline = "Paulovich.NET"
    description = ".NET Development and Software Architecture"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

# Social networks
  email = "ivan@paulovich.net"
  github = "ivanpaulovich"
  twitter = "ivanpaulovich"
  linkedin = "ivanpaulovich"
  facebook = "ivanpaulovich"
  instagram = "ivanpaulovich"
  youtube = "ivanpaulovich"

[Permalinks]
    post = "/:year/:month/:day/:filename/"