## Basic Configuration
baseurl = "https://paulovich.net/"
languageCode = "en"
title = "Paulovich.NET"
theme = "ghostwriter"
copyright = "Ivan Paulovich"
disqusShortname = "paulovichdotnet"
googleAnalytics = "UA-27176166-1"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Ivan Paulovich"
    profile = "https://github.com/ivanpaulovich"

[Taxonomies]
    tag = "tags"

## Site Settings
[params]
    intro = true
    headline = "Paulovich.NET"
    description = "Development and Architecture"
    github = "https://github.com/ivanpaulovich"
    linkedin = "https://linkedin.com/in/ivanpaulovich/"
    twitter = "https://twitter.com/ivanpaulovich"
    email = "ivan@paulovich.net"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4